name: web_ui
author: "Web UI Authors <web-ui-dev@dartlang.org>"
homepage: https://github.com/dart-lang/web-ui
description: An easy way to build web apps in Dart.
version: 0.4.9+2
dependencies:
  args: ">=0.4.5"
  analyzer_experimental: ">=0.5.12"
  browser: ">=0.4.5"
  logging: ">=0.4.5"
  pathos: ">=0.4.5"
  unittest: ">=0.4.5"
  # Pin these github packages so we don't get breaks from publishing them:
  csslib: ">=0.4.7 <0.4.8"
  html5lib: ">=0.4.3 <0.4.4"
  source_maps: ">=0.4.5"
dev_dependencies:
  js: any
  benchmark_harness: ">=1.0.2 <1.0.3"
environment:
  sdk: ">=0.5.12"
